### ISSUE TITLE
Release version 2.0.3 to NuGet feed of Optimizely

### ISSUE THREAD

**Issue by rolandv4net** [Geta/Geta.EPi.HotspotsEditor#12]
Hi there, the latest version published to the nuget feed of Optimizely is version 1.2.0.
However on github the latest version is 2.0.3. Is it possible to push that version to the Optimizely NuGet?

**Comment by svenrog** [comment]
https://nuget.optimizely.com/package/?id=Geta.EPi.HotspotsEditor
